volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:
  
services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    mem_limit: 512m
    depends_on:
      - foodgram_db
    env_file: .env
    build: ../backend
    volumes:
      - foodgram_static:/backend_static/
      - foodgram_media:/app/backend_media/

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static:/static/

  nginx:
    container_name: foodgram-proxy
    mem_limit: 256m
    build: ./nginx/
    env_file: .env
    volumes:
      - foodgram_static:/staticfiles
      - media_kittygram:/media

    ports:
      - 8080:80
    depends_on:
      - backend