version: '3.8'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  load_ingredients_tags:
    container_name: foodgram-load-ingredients-tags
    depends_on:
      - foodgram_db
    env_file: .env
    build: ../backend
    volumes:
      - ../data/:/prepared_data/
    command: >
      sh -c "echo 'Loading ingredients ...' && python /app/manage.py load_ingredients /prepared_data/ingredients.json && \
      echo 'Loading tags ...' && python /app/manage.py load_tags /prepared_data/tags.json"

  backend:
    container_name: foodgram-backend
    depends_on:
      - foodgram_db
      - load_ingredients_tags
    env_file: .env
    build: ../backend
    volumes:
      - ../data/:/prepared_data/
      - foodgram_static:/backend_static/
      - foodgram_media:/app/media
    command: sh -c "echo 'Collecting static files...' && python /app/manage.py collectstatic --noinput && \
      echo 'Applying migrations...' && python /app/manage.py migrate && \
      echo 'Copying collected static files...' && cp -r /app/collected_static/. /backend_static/static/ && \
      echo 'Starting Gunicorn server...' && gunicorn --bind 0.0.0.0:8080 foodgram_project.wsgi:application"

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - foodgram_static:/static/
    command: cp -r /app/build/. /static/

  nginx:
    container_name: foodgram-proxy
    build: ./nginx/
    env_file: .env
    volumes:
      - foodgram_static:/staticfiles
      - foodgram_media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - "8080:80"
    depends_on:
      - backend
