
volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:
  
services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    depends_on:
      - foodgram_db
    env_file: .env
    image: attame/foodgram_backend
    volumes:
      - foodgram_static:/backend_static/
      - foodgram_media:/app/backend_media/
      - ../data/:/prepared_data/
    command: sh -c "python /app/manage.py collectstatic --noinput && python /app/manage.py migrate && cp -r /app/collected_static/. /backend_static/static/ && gunicorn --bind 0.0.0.0:8080 backend.wsgi"

  frontend:
    container_name: foodgram-front
    image: attame/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static:/static/

  nginx:
    container_name: foodgram-proxy
    mem_limit: 256m
    image: attame/foodgram_gateway
    env_file: .env
    volumes:
      - foodgram_media:/media/
      - foodgram_static:/static/
    ports:
      - "8080:80"
    depends_on:
      - backend
