volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:
  
services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    depends_on:
      - foodgram_db
    env_file: .env
    build: ../backend
    volumes:
      - ../data/:/prepared_data/
      - foodgram_static:/backend_static/
      - foodgram_media:/app/backend_media/
    command: sh -c "python /app/manage.py collectstatic --noinput && python /app/manage.py migrate && cp -r /app/collected_static/. /backend_static/static/ && gunicorn --bind 0.0.0.0:8080 backend.wsgi"

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static:/static/

  gateway:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
      - frontend
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - foodgram_media:/media/
      - foodgram_static:/static/
      - ../docs/:/usr/share/nginx/html/api/docs/
