version: '3.8'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  migrate:
    container_name: foodgram-migrate
    depends_on:
      - foodgram_db
    env_file: .env
    build: ../backend
    command: sh -c "python /app/manage.py migrate && python /app/manage.py collectstatic --noinput"
  
  backend:
    container_name: foodgram-backend
    depends_on:
      - foodgram_db
      - migrate
    env_file: .env
    build: ../backend
    volumes:
      - foodgram_static:/backend_static/
      - foodgram_media:/app/backend_media/
      - ../data/:/prepared_data/
    command: gunicorn --bind 0.0.0.0:8080 backend.wsgi

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /static/
    volumes:
      - foodgram_static:/static/

  nginx:
    container_name: foodgram-proxy
    build: ./nginx/
    env_file: .env
    volumes:
      - foodgram_static:/staticfiles
      - foodgram_media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8080:80
    depends_on:
      - backend
