
volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:
  
services:
  foodgram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    depends_on:
      - foodgram_db
    env_file: .env
    image: attame/foodgram_backend
    volumes:
      - ../data/:/prepared_data/
      - foodgram_static:/backend_static/
      - foodgram_media:/app/backend_media/
    command: sh -c "echo 'Loading ingredients...' && python /app/manage.py load_ingredients /prepared_data/ingredients.json && \
      echo 'Collecting static files...' && python /app/manage.py collectstatic --noinput && \
      echo 'Applying migrations...' && python /app/manage.py migrate && \
      echo 'Copying collected static files...' && cp -r /app/collected_static/. /backend_static/static/ && \
      echo 'Starting Gunicorn server...' && gunicorn --bind 0.0.0.0:8080 foodgram_project.wsgi:application"




  frontend:
    container_name: foodgram-front
    image: attame/foodgram_frontend
    volumes:
      - foodgram_static:/static/
    command: cp -r /app/build/. /static/

  nginx:
    container_name: foodgram-proxy
    mem_limit: 256m
    image: attame/foodgram_gateway
    env_file: .env
    volumes:
      - foodgram_media:/media/
      - foodgram_static:/static/
    ports:
      - "8080:80"
    depends_on:
      - backend
