# Generated by Django 3.2.3 on 2025-04-14 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_shortrecipeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message=('Время приготовления не может быть меньше 1',)), django.core.validators.MaxValueValidator(1000, message=('Время приготовления не может быть больше 1000',))], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='shortrecipeurl',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_url', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
