# Generated by Django 4.2.19 on 2025-02-18 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                help_text="Обязательное поле. Максимальное количество символов: 150",
                max_length=150,
                unique=True,
                validators=[django.core.validators.MaxLengthValidator(150)],
                verbose_name="Уникальный юзернейм",
            ),
        ),
    ]
