# Generated by Django 4.2.19 on 2025-02-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                help_text="Обязательное поле. Максимальное количество символов: 150",
                max_length=150,
                unique=True,
                verbose_name="Уникальный юзернейм",
            ),
        ),
    ]
