# Generated by Django 4.2.19 on 2025-02-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="unique_subscription",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="cannot_subscription_self",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"), name="Вы уже подписаны на данного автора"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("author")), _negated=True),
                name="Нельзя подписаться на себя",
            ),
        ),
    ]
